// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnjtdjgexsvfpkzqypbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuanRkamdleHN2ZnBrenF5cGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDczODEsImV4cCI6MjA2ODUyMzM4MX0.beQqwWkv5D9FQ6axSWx0DdSBxgD_oUyPS31f1kHX7jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});